apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::386047805599:role/poc-eks20220122235236763500000009
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::386047805599:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_a5cc149a86961c90
      username: devops:{{SessionName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::386047805599:role/codebuild-eks
      username: codebuild-eks
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-22T23:52:39Z"
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1910461"
  uid: 64f543ed-fd61-4cad-8072-3618fa8e725f
