apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-cpu-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-cpu-load
      environment: testing
  template:
    metadata:
      labels:
        app: rest-cpu-load
        environment: testing
    spec:
      containers:
        - name: rest-cpu-load
          image: 386047805599.dkr.ecr.us-east-1.amazonaws.com/poc-boletia:latest
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 8080
              name: http
          type: LoadBalancer
          livenessProbe:
            exec:
              command:
              - ls
            initialDelaySeconds: 70
            timeoutSeconds: 10
            failureThreshold: 10 